name: 'Test'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: halaslabs/laravel-test-runner@v1
        with:
          php-version: 8.2